version: '3.8'

services:
  backend:
    build: ./backend
    container_name: lab_knowledge_backend
    restart: always
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    ports:
      - "5003:5003"
    environment:
      - FLASK_CONFIG=production
      - FLASK_APP=run.py
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: lab_knowledge_frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5003
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_data: 