"""add source_url to tech_summaries

Revision ID: 23a8bb636e7e
Revises: 2585d630f1a9
Create Date: 2025-03-13 17:10:47.419957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a8bb636e7e'
down_revision = '2585d630f1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_summaries', schema=None) as batch_op:
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
