"""Add original_file_name to Achievement model

Revision ID: 2585d630f1a9
Revises: 983337e21d1b
Create Date: 2025-03-11 11:25:10.029345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2585d630f1a9'
down_revision = '983337e21d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_file_name', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('original_file_name')

    # ### end Alembic commands ###
